server:
  port: 8888

cloud:
  eureka-host: localhost
  processing-service-url: http://localhost:8081
  currency-service-url: http://localhost:8080

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: currency-service
          uri: ${cloud.currency-service-url}
          predicates:
            - Path=/currency/**
        - id: exchange-processing-service
          uri: ${cloud.processing-service-url}
          predicates:
            - Path=/processing/**

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka




